version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        links:
            - fpm
        volumes:
            - ./:/var/www/pcom
            - ./images/nginx/vhost.conf:/etc/nginx/conf.d/laravel.conf
        working_dir:
            /var/www/pcom
    fpm:
        build: ./images/php-fpm
        ports:
            - "9000:9000"
        links:
            - db
        volumes:
            - ./:/var/www/pcom
        working_dir:
            /var/www/pcom

    db:
        image: mysql:5.7
        ports:
                - "3306:3306"
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel

volumes:
    data:
